# Generated by Django 5.0.4 on 2024-05-02 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=5)),
                ('number', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=1)),
                ('phone', models.CharField(max_length=50)),
                ('date_born', models.DateField()),
                ('identity_document', models.OneToOneField(db_column='id_identity_docum', on_delete=django.db.models.deletion.CASCADE, to='user.identitydocument')),
            ],
        ),
    ]
